In [195]:
%matplotlib inline


In [196]:
y_hat = np.linspace(-1,1,num=20); 
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [197]:
y = np.linspace(0,1,num=20);
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [198]:
y.shape

(20,)

In [199]:
y_hat.shape

(20,)

In [200]:
y.ndim

1

In [201]:
y_hat.ndim

1

##### Mean Absolute Error 

given n = 20, y_hat, y
Pseudocode
Loss value = (1/20) x Summation absolute difference of Ys
Absolute Difference = |y_hat - y)|

In [216]:


Absolute_Difference = (abs(y_hat - y));

Sum = np.sum(Absolute_Difference);

L = 1/n * Sum;

print("MAE =",L);

MAE = 0.49999999999999994


##### Mean Squared Error 

Pseudocode

L = ((1/20) * Summation of differences of Ys in one array)
Differences of Ys in the array = (y_hat + (- y))^2

In [217]:
y_hat = np.linspace(-1,1,num=20); 

y = np.linspace(0,1,num=20);

N = 20;

Sum = np.sum((y_hat - y)**2);

L = 1/N * Sum;

print('MSE = ',L);

MSE =  0.3421052631578948


##### Mean Squared Logarithmic Error: 
Pseudocode
    L = ((1/n) * SUMMATION of [(log(y_hat+1) - ( log(y+1)))^2]
    

In [218]:

array = (np.log(y_hat + 1) - np.log(y + 1))**2
Sum = np.sum(array[1:-1]);

L = 1/n * Sum;

print('MSLE = ',L);

MSLE =  0.6704976788287295


C:\Users\User\AppData\Local\Temp\ipykernel_17116\381462384.py:1: RuntimeWarning: divide by zero encountered in log
  array = (np.log(y_hat + 1) - np.log(y + 1))**2


##### Mean Absolute Percentage Error:
n=20
    L = 100%/n * (absolute((y_hat - y)/y)

In [219]:

Quotients = abs((y_hat-y)/y);

Sum = np.sum(Quotients[1:-1]);

L =( 100 * Sum) / n;
 
print('MAPE = ',L,"%")

MAPE =  242.03526742864983 %


C:\Users\User\AppData\Local\Temp\ipykernel_17116\1636896297.py:1: RuntimeWarning: divide by zero encountered in true_divide
  Quotients = abs((y_hat-y)/y);


Part 2

##### Create a 1d array M {1, 2, …16} using the arange function

In [220]:
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

###### Reshape M into 4x4 array and store it to N

In [221]:
N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Get the 2nd row of N

In [222]:
N[1:2,0:5]

array([[5, 6, 7, 8]])

##### Get the minimum values for each column of N

In [211]:
np.min(N, axis=0)

array([1, 2, 3, 4])

##### Get the locations of the minimum values for each column of N


In [212]:
np.argmin(N, axis=0)

array([0, 0, 0, 0], dtype=int64)

##### Get the average of the whole matrix



In [213]:
average(N)

8.5

##### Create a vector V with 4 elements, each element is 1


In [214]:
V = np.array([1,1,1,1])
V

array([1, 1, 1, 1])

##### Take the dot product of N and V

In [215]:
np.dot(N,V)

array([10, 26, 42, 58])